name: Nonpo Regression Automation

on:
  push:
    branches:
      - main   # Trigger only when code is pushed to main branch

jobs:
  test:
    runs-on: windows-latest   # using Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run TestNG Tests
        run: mvn -Dsurefire.suiteXmlFiles=testng.xml test

      - name: Upload TestNG Reports
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: target/surefire-reports
